### ISSUE TITLE
getting to run in digitalocean

### ISSUE THREAD

**Issue by mgiraldo** [sneezymud/sneezymud-docker#7]
i'm following the instructions to run sneezy on digitalocean. i go through all the steps which seem to go ok and when checking the logs (step 7) i get multiple of these:

`sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied`

is this expected? how do i test sneezy itself after install?

**Comment by cizra** [comment]
I've never tried digitalocean, but it works fine on my home computer, and
Azure.
That error is not expected.
Can you paste the full log?

**Comment by mgiraldo** [comment]
where's that file? when i execute `docker-compose logs -f sneezy` i get just a bunch of:

```
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
sneezy    | cp: cannot create regular file 'sneezy.cfg': Permission denied
```

**Comment by cizra** [comment]
I really don't know what's going on there. Are the file permissions OK? is
the underlying partition mounted in RW mode? Can you hop on our Discord
https://discord.gg/JGQvmRr and discuss it there?

**Comment by mgiraldo** [comment]
well i'm just following the instructions in the readme, not really an advanced docker user.

**Comment by cizra** [comment]
I have a hypothesis — perhaps your UID and the Sneezy user's UID don't
match? Are you running these setup scripts as root?

**Comment by mgiraldo** [comment]
yes. i believe so

**Comment by cizra** [comment]
That's the cause of the issue, then. Inside Docker container, commands are run as user sneezy with UID=1000, it doesn't have permissions to write to the dir.

At this point I'd delete the whole mess (including any state in Docker) and re-run the whole setup as a regular user.

**Comment by mgiraldo** [comment]
i will try this. thanks
